/*
 * MDSCreate.java
 *
 * Created on July 12, 2010, 12:05 PM
 */

package bankingapp;

import bankingapp.MdsDetails;
import bankingapp.Mds;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author  s
 */
public class MDSCreate extends javax.swing.JInternalFrame {
    
    /** Creates new form MDSCreate */
    int installmentsInt ;
    public MDSCreate() {
        initComponents();
        this.setVisible(false);
        String installments = JOptionPane.showInputDialog("Enter Number of Installments");
        
        try{
        installmentsInt = Integer.parseInt(installments.trim());
        }
        catch(Exception e){
            installments = JOptionPane.showInputDialog("Enter A valid Integer");
            installmentsInt = Integer.parseInt(installments.trim());
        }
        JTable table = new JTable();
        String[] columns = {"Installment No.","Installment Amt.","Amount"};
        Integer[][] data = new Integer[installmentsInt][];
        for(int i=0;i<installmentsInt;i++){
            Integer d[] = {(i+1),null,null};
            data[i] = d;
        }
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        DefaultTableModel dtm = new DefaultTableModel(data,columns);
        jTable1.setModel(dtm);
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = javax.persistence.Persistence.createEntityManagerFactory("BankingAppPU").createEntityManager();
        nameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bankingapp.BankingApp.class).getContext().getResourceMap(MDSCreate.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        nameText.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        nameText.setText(resourceMap.getString("nameText.text")); // NOI18N
        nameText.setName("nameText"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(bankingapp.BankingApp.class).getContext().getActionMap(MDSCreate.class, this);
        jButton1.setAction(actionMap.get("saveMDS")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setFont(resourceMap.getFont("jTable1.font")); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void saveMDS() {
        try {
            entityManager1.getTransaction().begin();
            Mds m = new Mds();
            m.setName(nameText.getText().trim());
            entityManager1.persist(m);
            
            TableModel tm = jTable1.getModel();
            int lastId = Utils.getMaxId("mds");
            lastId++;
            for (int i = 0; i < installmentsInt; i++) {
                Double installmentAmount = Double.parseDouble((String) tm.getValueAt(i,1));
                Double amountGetting = Double.parseDouble((String) tm.getValueAt(i,2));
                MdsDetails mdsd = new MdsDetails();
                mdsd.setAmount(amountGetting);
                mdsd.setInstallmentAmount(installmentAmount);
                mdsd.setInstallment(i+1);
                mdsd.setMdsId(lastId);
                entityManager1.persist(mdsd);
            }

            entityManager1.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "MDS has been created");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"An error occured ."+e.getMessage(), "ERROR" ,JOptionPane.ERROR_MESSAGE);
            if(entityManager1.getTransaction().isActive()){
                entityManager1.getTransaction().rollback();
            }
            return;
        }
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MDSCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables
    
}
