/*
 * SBNew.java
 *
 * Created on June 1, 2010, 10:22 PM
 */

package bankingapp;

import bankingapp.Accounts;
import bankingapp.Members;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author  s
 */
public class SBNew extends javax.swing.JInternalFrame {
    private EntityManager BankingPUEntityManager;
    private int sbSchemeId;
    /** Creates new form SBNew */
    public SBNew() {
        initComponents();
        BankingPUEntityManager = javax.persistence.Persistence.createEntityManagerFactory("BankingAppPU").createEntityManager();
        Query schemeId = BankingPUEntityManager.createQuery("SELECT s.id from Schemes s where s.scheme = 'SB'");
        Integer id = (Integer) schemeId.getSingleResult();
        sbSchemeId= id;
        Query q = BankingPUEntityManager.createQuery("SELECT max(a.accountNumber) from Accounts a where a.schemeId = "+sbSchemeId); 
        Object o = q.getSingleResult();
        accNo.setText(o==null?"1":Integer.parseInt(o.toString())+1+"");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criteriaCombo = new javax.swing.JComboBox();
        pkText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        detailsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accNo = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bankingapp.BankingApp.class).getContext().getResourceMap(SBNew.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        criteriaCombo.setFont(resourceMap.getFont("criteriaCombo.font")); // NOI18N
        criteriaCombo.setModel(new DefaultComboBoxModel(UserTypeComboItem.constructMenuItem()));
        criteriaCombo.setName("criteriaCombo"); // NOI18N

        pkText.setFont(resourceMap.getFont("criteriaCombo.font")); // NOI18N
        pkText.setText(resourceMap.getString("pkText.text")); // NOI18N
        pkText.setName("pkText"); // NOI18N
        pkText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pkTextKeyReleased(evt);
                pkTextKeyReleased1(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(bankingapp.BankingApp.class).getContext().getActionMap(SBNew.class, this);
        jButton1.setAction(actionMap.get("createSBAccount")); // NOI18N
        jButton1.setFont(resourceMap.getFont("criteriaCombo.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        detailsLabel.setText(resourceMap.getString("detailsLabel.text")); // NOI18N
        detailsLabel.setName("detailsLabel"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("criteriaCombo.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        accNo.setFont(resourceMap.getFont("criteriaCombo.font")); // NOI18N
        accNo.setText(resourceMap.getString("accNo.text")); // NOI18N
        accNo.setName("accNo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(criteriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(accNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pkText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(detailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pkTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pkTextKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_pkTextKeyReleased

    private void pkTextKeyReleased1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pkTextKeyReleased1
        List l = getUser();
        if(l.size()!=0){
            jButton1.setEnabled(true);
            Members m = (Members) l.get(0);
            detailsLabel.setText("<html>Username :"+m.getUsername()+" <br /> Membership No. :"+m.getNumber()+" </html>");
        }
        else{
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_pkTextKeyReleased1

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO account number duplicate check
            Members m = (Members) getUser().get(0);
            Accounts newAcc = new Accounts();
            newAcc.setAccountNumber(Integer.parseInt(accNo.getText()));
            newAcc.setClosed(0);
            newAcc.setMemberId(m.getId());
            newAcc.setSchemeId(sbSchemeId);
            BankingPUEntityManager.getTransaction().begin();
            BankingPUEntityManager.persist(newAcc);
            BankingPUEntityManager.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "Account has been Created");
            this.setClosed(true);//GEN-LAST:event_jButton1ActionPerformed
        } catch (PropertyVetoException ex) {
            Logger.getLogger(SBNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
List getUser(){
    Query q = BankingPUEntityManager.createQuery("SELECT m  FROM Members m where m."+((UserTypeComboItem)criteriaCombo.getSelectedItem()).getColumn()+" = '"+pkText.getText().trim()+"'");
        List l = q.getResultList();
        return l;
}    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNo;
    private javax.swing.JComboBox criteriaCombo;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pkText;
    // End of variables declaration//GEN-END:variables
    
}
