/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SBTransact.java
 *
 * Created on 03-Jun-2010, 12:23:38
 */
package bankingapp;

import bankingapp.Accounts;
import bankingapp.Transactions;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author flyhigh
 */
public class SBTransact extends javax.swing.JInternalFrame {

    /** Creates new form SBTransact */
    private int sbSchemeId;

    public SBTransact() {
        initComponents();
        Query schemeId = entityManager1.createQuery("SELECT s.id from Schemes s where s.scheme = 'SB'");
        Integer id = (Integer) schemeId.getSingleResult();
        sbSchemeId = id;
    }

    public Accounts getSelectedAccount() {
        if (accountNumberText.getText() == null || accountNumberText.getText().trim() == null || accountNumberText.getText().trim().length() == 0) {
            return null;
        }
        String sql = "SELECT a FROM Accounts a where a.accountNumber = " + accountNumberText.getText().trim() + " and a.schemeId = " + sbSchemeId;
        System.out.println(sql);
        Query q = entityManager1.createQuery(sql);
        List l = q.getResultList();
        if (l.size() != 0) {
            return (Accounts) l.get(0);
        } else {
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        entityManager1 = javax.persistence.Persistence.createEntityManagerFactory("BankingAppPU").createEntityManager();
        jLabel1 = new javax.swing.JLabel();
        accountNumberText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bankingapp.BankingApp.class).getContext().getResourceMap(SBTransact.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        accountNumberText.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        accountNumberText.setText(resourceMap.getString("accountNumberText.text")); // NOI18N
        accountNumberText.setName("accountNumberText"); // NOI18N
        accountNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountNumberTextKeyReleased(evt);
            }
        });

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        amountText.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        amountText.setText(resourceMap.getString("amountText.text")); // NOI18N
        amountText.setName("amountText"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amountText, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(accountNumberText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(188, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void accountNumberTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNumberTextKeyReleased
        jButton1.setEnabled(getSelectedAccount() != null);
    }//GEN-LAST:event_accountNumberTextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Transactions t = new Transactions();

        t.setDeposit(Double.parseDouble(amountText.getText().trim()));

        t.setAccountId(getSelectedAccount().getId());
        t.setUserId(getSelectedAccount().getMemberId());
        entityManager1.getTransaction().begin();
        entityManager1.persist(t);
        entityManager1.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Transaction has been made");
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberText;
    private javax.swing.JTextField amountText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
